platform :ios, '6.0'
pod 'AFNetworking', '~> 2.3.1'
pod 'DCKeyValueObjectMapping', '~> 1.4'
pod 'TMCache', '~> 1.2.0'
pod 'UIAlertView+Blocks', '~> 0.7'
pod 'iOS7Colors'
pod 'FormatterKit', '~> 1.4'
pod 'GPUImage'
pod 'TSMessages'
pod 'JSONModel'
pod 'SVWebViewController', '~> 0.1'
pod 'SVProgressHUD'
